version: '3'
services:
  rest_app:
    environment:
      - USER_NAME=${DB_USERNAME}
      - PASSWORD=${DB_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_USER: ${DB_USERNAME}
        DB_PASS: ${DB_PASSWORD}
    ports:
      - "5000:5000"
    expose:
      - 5000