apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: {{ .Values.image.repository }}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000